# Generated by Django 2.1.7 on 2019-03-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
