# Generated by Django 2.1.7 on 2019-03-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='name',
            new_name='user',
        ),
    ]
