# Generated by Django 2.1.7 on 2019-03-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190313_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecomments',
            old_name='name',
            new_name='user',
        ),
    ]
