# Generated by Django 2.1.7 on 2019-03-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190313_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户课程', 'verbose_name_plural': '用户课程'},
        ),
    ]
